---

- hosts: k8s-cluster
  roles:
    - kubesphere-defaults
    - prepare/nodes
  
- hosts: kube-master[0]
  roles:
    - kubesphere-defaults
    - { role: ks-devops/harbor, when: "harbor_enable == true" }
    - { role: ks-devops/gitlab, when: "gitlab_enable == true" }